In [1]:
import pandas as pd

In [2]:
REGLES = './_output/regles.csv'
REGLES_CLEAN = './_output/regles_clean.csv'

In [3]:
df_regles = pd.read_csv(REGLES)
df_regles.set_index('source_id', inplace=True)
df_regles.head()

,niveau,montant,unite,ordre,order_niveau_regle,cible,flag_chiffre_independant_des_benefs,exception,cible_si_independant,flag_optionel,min,max,flag_cible_multiple,flag_delegation
source_id,,,,,,,,,,,,,,
304815,1,5,%,1,1,intérêt aux actions,True,False,False,False,False,False,False,False
304815,1,10,%,2,2,réserve,False,False,False,False,False,False,False,False
304815,1,5,%,3,3,Conseil d’administration,False,False,False,False,False,False,False,False
304815,1,3,%,4,4,Directeur,False,False,False,False,False,False,False,False
304815,1,2,%,5,5,Caisse de retraite des employés,False,False,False,False,False,False,False,False

In [4]:
df_regles.drop('order_niveau_regle', axis=1, inplace=True)

In [5]:
def falseToEmpty(val):
    if (val == 'False' or val == False):
        return ''
    elif(type(val) is str and  len(val) > 250): # si jamais la taille est supérieure à un string
        return val[:250]
    return val

In [6]:
df_regles['exception'] = df_regles.apply(lambda row: falseToEmpty(row.exception), axis=1)
df_regles['cible_si_independant'] = df_regles.apply(lambda row: falseToEmpty(row.cible_si_independant), axis=1)
df_regles['min'] = df_regles.apply(lambda row: falseToEmpty(row['min']), axis=1)
df_regles['max'] = df_regles.apply(lambda row: falseToEmpty(row['max']), axis=1)
df_regles.head()

,niveau,montant,unite,ordre,cible,flag_chiffre_independant_des_benefs,exception,cible_si_independant,flag_optionel,min,max,flag_cible_multiple,flag_delegation
source_id,,,,,,,,,,,,,
304815,1,5,%,1,intérêt aux actions,True,,,False,,,False,False
304815,1,10,%,2,réserve,False,,,False,,,False,False
304815,1,5,%,3,Conseil d’administration,False,,,False,,,False,False
304815,1,3,%,4,Directeur,False,,,False,,,False,False
304815,1,2,%,5,Caisse de retraite des employés,False,,,False,,,False,False

In [7]:
def cleanTrueFalse(val):
    if (val == 'True' or val == True):
        return 1
    else:
        return 0

In [8]:
df_regles['flag_chiffre_independant_des_benefs'] = df_regles.apply(lambda row: cleanTrueFalse(row.flag_chiffre_independant_des_benefs), axis=1)
df_regles['flag_optionel'] = df_regles.apply(lambda row: cleanTrueFalse(row.flag_optionel), axis=1)
df_regles['flag_cible_multiple'] = df_regles.apply(lambda row: cleanTrueFalse(row.flag_cible_multiple), axis=1)
df_regles['flag_delegation'] = df_regles.apply(lambda row: cleanTrueFalse(row.flag_delegation), axis=1)
df_regles.head()

,niveau,montant,unite,ordre,cible,flag_chiffre_independant_des_benefs,exception,cible_si_independant,flag_optionel,min,max,flag_cible_multiple,flag_delegation
source_id,,,,,,,,,,,,,
304815,1,5,%,1,intérêt aux actions,1,,,0,,,0,0
304815,1,10,%,2,réserve,0,,,0,,,0,0
304815,1,5,%,3,Conseil d’administration,0,,,0,,,0,0
304815,1,3,%,4,Directeur,0,,,0,,,0,0
304815,1,2,%,5,Caisse de retraite des employés,0,,,0,,,0,0

In [9]:
df_regles.to_csv(REGLES_CLEAN)